#!/usr/bin/env python3
"""Generator for the A3197S PLL frequency->register-code table.

Implements the verified register bitfield model (see pll_cpm_table.c's
header comment for the full derivation and verification method):

    REFDIV      = (reg >> 1) & 0x3F
    FBDIV       = (reg >> 7) & 0x1FF
    POSTDIV_EXP = (reg >> 17) & 0x7        POSTDIV = 1 << POSTDIV_EXP
    ENABLE      = reg & 1
    Fout = 24MHz * FBDIV / (2 * REFDIV * POSTDIV)

This script's `SAFE_REGIONS` bounds are the observed extents of the
original recovered vendor table -- they are NOT derivable from the VCO
constraint alone (a pure "every combination whose VCO lands in
[954,1896] MHz" rule produces 948 valid combinations, not the vendor's
293; the specific range/resolution per band is a vendor calibration
choice, not physics). That's disclosed here rather than implied away.

--generate emits the safe, vendor-range-matching table (99-600MHz,
293 rows, byte-identical to the original array this replaces).

--extend-700 additionally emits an EXTRAPOLATED reference table
covering ~600-700MHz, generated by continuing the exact same
arithmetic pattern beyond the vendor's observed cutoff, while staying
inside the measured VCO band. This range has NEVER been validated on
real silicon -- the original table stops at 600MHz, and nothing in
this project has ever run this chip above ~480MHz. The extended output
is written to a file that is deliberately NOT under rtos_core/src/ or
rtos_core/include/ (the Makefile's `SRCS := $(wildcard src/*.c)` would
pick up anything placed in src/) and is not referenced by any other
source file. Do not wire it into asic_engine.c or move it into src/
without real hardware validation first.

--extend-low emits an EXTRAPOLATED reference table covering ~50-98MHz,
below the vendor's observed 99MHz floor. Two different confidence
levels are mixed in here:
  - 60-98MHz extends POSTDIV_EXP=4 (D=16), the SAME divider value the
    real table already uses at 99-118.5MHz, just further down its own
    FBDIV range within the measured VCO band. Same category as
    --extend-700.
  - 50-59MHz requires POSTDIV_EXP=5 (D=32), a divider value that has
    NEVER appeared anywhere -- not in the vendor table, not in the
    --extend-700 output, not in any real capture. This is a genuinely
    new, unobserved field value, not just an unused range of a known
    one -- treat it with correspondingly less confidence.
Nothing in this project has ever run this chip below ~99MHz. Same
isolation rule as --extend-700: not written into src/, not referenced
anywhere, not safe to use without real hardware validation.
"""
import argparse

VCO_MIN, VCO_MAX = 954.0, 1896.0

# (postdiv_exp, [(refdiv, fbdiv_lo, fbdiv_hi_inclusive, fbdiv_step), ...])
# These fbdiv bounds are the vendor table's observed extents (see module
# docstring) -- not independently derivable from physics.
SAFE_REGIONS = [
    (4, [(1, 132, 158, 2)]),                          # D=16: 99-118.5MHz
    (3, [(1, 80, 158, 1)]),                            # D=8:  120-237.5MHz (FF=03/83 merged: FBDIV counts by 1)
    (2, [(1, 80, 158, 1), (2, 159, 315, 2)]),          # D=4:  238.5-474MHz, + finer class 477-597MHz... see note
    (1, [(1, 80, 100, 1), (2, 159, 199, 2)]),          # D=2:  480-600MHz
]
# NOTE: SAFE_REGIONS is intentionally written in terms of the verified
# FBDIV/REFDIV fields directly (not re-derived here); it is checked
# byte-for-byte against the original array by verify_against_original()
# below before being trusted for anything.

def make_row(refdiv, fbdiv, postdiv_exp):
    postdiv = 1 << postdiv_exp
    reg = 0x90000000 | (postdiv_exp << 17) | (fbdiv << 7) | (refdiv << 1) | 1
    fout = 24.0 * fbdiv / (2 * refdiv * postdiv)
    return int(fout), reg, fout

def gen_safe():
    rows = []
    for postdiv_exp, classes in SAFE_REGIONS:
        region = []
        for refdiv, lo, hi, step in classes:
            for fbdiv in range(lo, hi + 1, step):
                freq, reg, fout = make_row(refdiv, fbdiv, postdiv_exp)
                region.append((fout, freq, reg))
        region.sort(key=lambda r: r[0])
        rows.extend((freq, reg) for fout, freq, reg in region)
    return rows

def gen_extended_700():
    """Continue the D=2 (postdiv_exp=1) region's same two classes (REFDIV=1
    consecutive FBDIV, REFDIV=2 odd FBDIV) past the vendor's 600MHz cutoff,
    stopping at 700MHz or the measured VCO band edge, whichever is first."""
    rows = gen_safe()
    postdiv_exp = 1
    postdiv = 1 << postdiv_exp
    extra = []
    # REFDIV=1 class: continue FBDIV upward from where SAFE_REGIONS left off (100)
    fbdiv = 101
    while True:
        vco = 24.0 * fbdiv / (2 * 1)
        fout = vco / postdiv
        if vco > VCO_MAX or fout > 700:
            break
        freq, reg, fout = make_row(1, fbdiv, postdiv_exp)
        extra.append((fout, freq, reg))
        fbdiv += 1
    # REFDIV=2 class: continue from where SAFE_REGIONS left off (199)
    fbdiv = 201
    while True:
        vco = 24.0 * fbdiv / (2 * 2)
        fout = vco / postdiv
        if vco > VCO_MAX or fout > 700:
            break
        freq, reg, fout = make_row(2, fbdiv, postdiv_exp)
        extra.append((fout, freq, reg))
        fbdiv += 2
    extra.sort(key=lambda r: r[0])
    return rows + [(freq, reg) for fout, freq, reg in extra]

def gen_extended_low():
    """Extend below the vendor's 99MHz floor: continue POSTDIV_EXP=4 (an
    already-used divider) down its own FBDIV range to the VCO band's
    lower edge (~60MHz), then continue further to ~50MHz using
    POSTDIV_EXP=5 -- a divider value that appears nowhere else."""
    rows = gen_safe()
    extra = []
    # POSTDIV_EXP=4, REFDIV=1: already-used divider, extend FBDIV downward
    # from where SAFE_REGIONS starts (132) to the VCO band's floor.
    postdiv_exp = 4
    postdiv = 1 << postdiv_exp
    fbdiv = 131
    while True:
        vco = 24.0 * fbdiv / (2 * 1)
        if vco < VCO_MIN:
            break
        freq, reg, fout = make_row(1, fbdiv, postdiv_exp)
        extra.append((fout, freq, reg))
        fbdiv -= 1
    # POSTDIV_EXP=5: unobserved divider value, both classes, bounded >=50MHz.
    postdiv_exp = 5
    postdiv = 1 << postdiv_exp
    for fbdiv in range(80, 159):
        vco = 24.0 * fbdiv / (2 * 1)
        if vco > VCO_MAX:
            break
        freq, reg, fout = make_row(1, fbdiv, postdiv_exp)
        if fout >= 50:
            extra.append((fout, freq, reg))
    for fbdiv in range(159, 317, 2):
        vco = 24.0 * fbdiv / (2 * 2)
        if vco > VCO_MAX:
            break
        freq, reg, fout = make_row(2, fbdiv, postdiv_exp)
        if fout >= 50:
            extra.append((fout, freq, reg))
    extra.sort(key=lambda r: r[0])
    return [(freq, reg) for fout, freq, reg in extra] + rows

def verify_against_original(rows, path):
    import re
    with open(path) as f:
        text = f.read()
    orig = [(int(m.group(1)), int(m.group(2), 16))
            for m in re.finditer(r'\{\s*(\d+)\s*,\s*(0x[0-9a-fA-F]+)\s*\}', text)]
    return rows == orig

def emit_c_array(rows, varname="cpm_table"):
    lines = [f"const uint32_t {varname}[{len(rows)}][2] =", "{"]
    for freq, reg in rows:
        lines.append(f"\t{{{freq},\t0x{reg:08x}}},")
    lines.append("};")
    return "\n".join(lines)

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--generate", action="store_true")
    ap.add_argument("--extend-700", action="store_true")
    ap.add_argument("--extend-low", action="store_true")
    ap.add_argument("--verify-against", metavar="PATH")
    args = ap.parse_args()

    if args.verify_against:
        rows = gen_safe()
        ok = verify_against_original(rows, args.verify_against)
        print(f"{len(rows)} rows generated; matches {args.verify_against}: {ok}")

    if args.generate:
        print(emit_c_array(gen_safe()))

    if args.extend_700:
        ext = gen_extended_700()
        safe = gen_safe()
        print(f"# safe (<=600MHz): {len(safe)} rows")
        print(f"# extended (<=700MHz): {len(ext)} rows ({len(ext)-len(safe)} rows above the vendor's validated 600MHz ceiling)")
        print(emit_c_array(ext, varname="cpm_table_UNVALIDATED_EXTENDED_700MHz"))

    if args.extend_low:
        low = gen_extended_low()
        safe = gen_safe()
        print(f"# safe (>=99MHz): {len(safe)} rows")
        print(f"# extended (<99MHz): {len(low)} rows ({len(low)-len(safe)} rows below the vendor's observed 99MHz floor)")
        print(emit_c_array(low, varname="cpm_table_UNVALIDATED_EXTENDED_LOW"))
